spring.application.name=fhk-security-server

# 서버 포트
server.port=81

# Maridb 연결 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PW}

# Data Jpa 방식
spring.jpa.hibernate.ddl-auto=update
# Batch Size
spring.jpa.properties.hibernate.default_batch_fetch_size=1000
# 실행되는 쿼리 콘솔 출력
spring.jpa.properties.hibernate.show_sql=true
# 콘솔창에 출력되는 쿼리를 가독성이 좋게 포맷팅
spring.jpa.properties.hibernate.format_sql=true
# 쿼리에 물음표로 출력되는 바인드 파라미터 출력
logging.level.org.hibernate.type.descriptor.sql=trace

# jwt access token
jwt.access-secret=${ACCESS_SECRET}
# 만료기간 15분=900000 / 24시간=86400000(일단 24시간)
jwt.access-expire-ms=900000
# jwt refresh token
jwt.refresh-secret=${REFRESH_SECRET}
# 만료기간 14일
jwt.refresh-expire-ms=1209600000

## redis
spring.data.redis.host=192.168.0.184
spring.data.redis.port=16379
spring.data.redis.password=${REDIS_PW}
